// CodeGenerator.cpp
#include "CodeGenerator.h"
#include <sstream>
#include <stdexcept>

namespace codegen {

using namespace std;
using namespace ir;

namespace {

string operandExpr(const Operand& operand) {
    // Operand::toString() already renders constants/variables/temps exactly
    // the way we want them to appear in generated C++ expressions.
    return operand.toString();
}

string opExpr(const Instruction& instr) {
    const auto& ops = instr.operands;
    ostringstream oss;
    switch (instr.op) {
        case Op::ADD: oss << operandExpr(ops[0]) << " + " << operandExpr(ops[1]); break;
        case Op::SUB: oss << operandExpr(ops[0]) << " - " << operandExpr(ops[1]); break;
        case Op::MUL: oss << operandExpr(ops[0]) << " * " << operandExpr(ops[1]); break;
        case Op::DIV: oss << operandExpr(ops[0]) << " / " << operandExpr(ops[1]); break;
        case Op::NEG: oss << "-" << operandExpr(ops[0]); break;
        case Op::SIN: oss << "sin(" << operandExpr(ops[0]) << ")"; break;
        case Op::COS: oss << "cos(" << operandExpr(ops[0]) << ")"; break;
        case Op::EXP: oss << "exp(" << operandExpr(ops[0]) << ")"; break;
        case Op::LOG: oss << "log(" << operandExpr(ops[0]) << ")"; break;
        case Op::POW: oss << "pow(" << operandExpr(ops[0]) << ", " << operandExpr(ops[1]) << ")"; break;
        default: throw runtime_error("CodeGenerator: unsupported op " + opName(instr.op));
    }
    return oss.str();
}

} // namespace

string CodeGenerator::generateFunction(const ir::IRFunction& func) {
    ostringstream oss;
    oss << "double " << func.name << "(";
    for (size_t i = 0; i < func.params.size(); ++i) {
        oss << "double " << func.params[i];
        if (i + 1 < func.params.size()) oss << ", ";
    }
    oss << ") {\n";

    for (const auto& instr : func.instructions) {
        oss << "    double t" << instr.resultId << " = " << opExpr(instr) << ";\n";
    }

    oss << "    return " << operandExpr(func.returnValue) << ";\n";
    oss << "}\n";
    return oss.str();
}

string CodeGenerator::generateStandaloneSource(const ir::IRFunction& func) {
    ostringstream oss;
    oss << "// Auto-generated by CodeGenerator (Member 4 module).\n";
    oss << "// Do not edit by hand - regenerate from IR instead.\n";
    oss << "#include <cmath>\n\n";
    oss << generateFunction(func);
    return oss.str();
}

} // namespace codegen
